CREATE TABLE user (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(45) NOT NULL
);

CREATE TABLE sector (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
);

CREATE TABLE user_sector (
  user_id INTEGER NOT NULL,
  sector_id INTEGER NOT NULL,
  FOREIGN KEY (user_id)
          REFERENCES USER ON DELETE RESTRICT,
  FOREIGN KEY (sector_id)
          REFERENCES sector ON DELETE RESTRICT
);
