
DROP SCHEMA PUBLIC CASCADE

CREATE TABLE user (
  id INTEGER NOT NULL PRIMARY KEY,
  username VARCHAR(45) NOT NULL,
  agreedtoterms BOOLEAN NOT NULL
);

CREATE TABLE sector (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  FOREIGN KEY (parent_sector_id)
    REFERENCES ROLE ON DELETE RESTRICT
);

CREATE TABLE user_sector (
  user_id INTEGER NOT NULL,
  sector_id INTEGER NOT NULL,
  FOREIGN KEY (user_id)
          REFERENCES USER ON DELETE RESTRICT,
  FOREIGN KEY (sector_id)
          REFERENCES SECTOR ON DELETE RESTRICT
);
